services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: chatbothm
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}