services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://chatbotHM_owner:npg_TGUIZp4P2jvl@ep-shy-paper-aco1cs3q-pooler.sa-east-1.aws.neon.tech/chatbotHM?sslmode=require
    image: chatbothm
    ports:
      - "3000:3000"
    env_file:
      - .env