services:

  chatbot-hm:
    build:
      context: ./
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: chatbot-hm
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}